/**
 * CustomProTable 组件样式变量 - TypeScript 常量
 * 从 Figma 设计稿自动生成
 *
 * Figma 链接: https://www.figma.com/design/h0gT5MlFnxNOmOIQVd1thT/
 * Node ID: 369-604 (AccountListContent)
 */

/* ===== CustomProTable 组件变量 ===== */

/* 表格容器 */
export const FIGMA_COMPONENT_PRO_TABLE_CARD_BG = '#ffffff';
export const FIGMA_COMPONENT_PRO_TABLE_CARD_RADIUS = 8;
export const FIGMA_COMPONENT_PRO_TABLE_CARD_SHADOW =
  '0px 1px 6px -1px rgba(0, 0, 0, 0.06)';

/* 工具栏 */
export const FIGMA_COMPONENT_PRO_TABLE_TOOLBAR_BG = '#ffffff';
export const FIGMA_COMPONENT_PRO_TABLE_TOOLBAR_HEIGHT = 48;
export const FIGMA_COMPONENT_PRO_TABLE_TOOLBAR_PADDING = 16;

/* 表头 (thead) */
export const FIGMA_COMPONENT_PRO_TABLE_THEAD_BG = '#fafafa';
export const FIGMA_COMPONENT_PRO_TABLE_THEAD_TEXT_COLOR = '#434343';
export const FIGMA_COMPONENT_PRO_TABLE_THEAD_FONT_SIZE = 13;
export const FIGMA_COMPONENT_PRO_TABLE_THEAD_FONT_WEIGHT = 500;
export const FIGMA_COMPONENT_PRO_TABLE_THEAD_PADDING = '12px 16px';

/* 表体 (tbody) */
export const FIGMA_COMPONENT_PRO_TABLE_TBODY_BG = '#ffffff';
export const FIGMA_COMPONENT_PRO_TABLE_TBODY_ALT_BG = '#fafafa';
export const FIGMA_COMPONENT_PRO_TABLE_TBODY_ROW_HOVER_BG = '#fafafa';
export const FIGMA_COMPONENT_PRO_TABLE_TBODY_CELL_PADDING = '12px 16px';
export const FIGMA_COMPONENT_PRO_TABLE_DIVIDER_COLOR = '#e8e8e8';
export const FIGMA_COMPONENT_PRO_TABLE_DIVIDER_WIDTH = 1;

/* 复选框 */
export const FIGMA_COMPONENT_PRO_TABLE_CHECKBOX_RADIUS = 2;
export const FIGMA_COMPONENT_PRO_TABLE_CHECKBOX_BORDER_COLOR = '#d9d9d9';
export const FIGMA_COMPONENT_PRO_TABLE_CHECKBOX_CHECKED_BG = '#1677ff';
export const FIGMA_COMPONENT_PRO_TABLE_CHECKBOX_CHECKED_BORDER = '#1677ff';

/* 状态徽章 */
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_ONLINE_BG = '#f6ffed';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_ONLINE_TEXT = '#52c41a';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_ONLINE_DOT = '#52c41a';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_INVALID_BG = '#fff2f0';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_INVALID_TEXT = '#ff4d4f';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_INVALID_DOT = '#ff4d4f';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_STOPPED_BG = '#f5f5f5';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_STOPPED_TEXT = '#8c8c8c';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_STOPPED_DOT = '#8c8c8c';
export const FIGMA_COMPONENT_PRO_TABLE_STATUS_RADIUS = 12;

/* 操作列 */
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_LINK_COLOR = '#1677ff';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_RADIUS = 4;
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_BORDER_COLOR = '#d9d9d9';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_TEXT_COLOR = '#595959';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_BORDER_WIDTH = 1;
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_DANGER_BORDER = '#ff4d4f';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_DANGER_TEXT = '#ff4d4f';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_PRIMARY_BORDER = '#1677ff';
export const FIGMA_COMPONENT_PRO_TABLE_ACTION_BUTTON_PRIMARY_TEXT = '#1677ff';

/* 选中信息区 */
export const FIGMA_COMPONENT_PRO_TABLE_SELECTION_BADGE_BG = '#1677ff';
export const FIGMA_COMPONENT_PRO_TABLE_SELECTION_BADGE_TEXT = '#ffffff';
export const FIGMA_COMPONENT_PRO_TABLE_SELECTION_LABEL_COLOR = '#595959';

/* 批量操作按钮 */
export const FIGMA_COMPONENT_PRO_TABLE_BATCH_BUTTON_RADIUS = 4;
export const FIGMA_COMPONENT_PRO_TABLE_BATCH_BUTTON_BORDER_WIDTH = 1;
